version: '3'

services:

  client:
    build:
      context: client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/usr/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  server:
    build:
      context: server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/usr/app
    ports:
      - ${NESTJS_PORT}:${NESTJS_PORT}
    environment:
      - NESTJS_PORT=${NESTJS_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DATABASE=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NODE_ENV=development
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - postgres-db:/var/lib/postgresql/data

  # Graphical front-end, similar to phpMyAdmin, to monitor postgreSQL
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres-db: 
